### ISSUE TITLE
`FetchConfig:use` middleware currently unused

### ISSUE THREAD

**Issue by bddvlpr** [cocreators-ee/apity#12]
Great project so far, works perfectly for my projects. Only feature it's missing is a middleware provider. I've noticed there's a config to apply middleware, yet it's unused as far as I can tell. Is this feature still planned?

**Comment by fbjorn** [comment]
Hi @bddvlpr, thanks for the feedback. Can you describe how exactly do you want to use middlewares with Apity? Or maybe give an example of such middleware. It will help us to provide a better answer or even implement it.

**Comment by bddvlpr** [comment]
For example, catching when a user is unauthorized for all API calls; every call has a possibility to throw a 401 when the user's token is expired. Using a middleware this could be handled and catched without having to define it for each individual request.

**Comment by zeecou** [comment]
Hey @bddvlpr may I know why did you close this issue as `not planned` given that you are the one that proposed it? I believe the use case with authentication is significant and would love to have such middleware available.

**Comment by bddvlpr** [comment]
Because this library is no longer being maintained. Personally, I would recommend you switch to [openapi-fetch](https://openapi-ts.dev/openapi-fetch/) as it does pretty much what this library does while still being maintained.
